" sets
set nocompatible
set backspace=2
set encoding=utf-8
set fileencoding=utf-8
filetype off
let $LANG='en'
set langmenu=none
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set smartindent
set smartcase
set ignorecase
set incsearch
set noswapfile
set nowrap
set number 
set relativenumber
set iskeyword+=-
set splitbelow
set splitright
set hlsearch
set noerrorbells
set scrolloff=10
set hidden
set path+=**
set t_Co=256
set background=dark
syntax on
